prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/pemberton-rank/configs/master/rubocop.yml"
    path: ".rubocop.yml"
  fetch:
  - url: "https://raw.githubusercontent.com/pemberton-rank/configs/master/reek.yml"
    path: ".reek.yml"
plugins:
  rubocop:
    enabled: true
  reek:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
