image: shkm/ruby-node:r2.5.3

pipelines:
  default:
    - step:
       name: Run tests
       script:
         - git remote set-url origin ${BITBUCKET_GIT_HTTP_ORIGIN}
         - bundle install --path vendor/bundle
         - bundle exec rails db:test:prepare
         - bundle exec rspec
         - git branch --no-track origin/master && PRONTO_BITBUCKET_SLUG=pembertonrank/common bundle exec pronto run -f bitbucket_pr -c origin/master
       services:
         - postgres
       caches:
         - bundler

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: root
  caches:
    bundler: vendor/bundle
