default: &default
  adapter: postgresql
  pool: 25
  host: 127.0.0.1
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: pr-common_development

test:
  <<: *default
  database: pr-common_test
